spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.springframework.data.redis : TRACE
    org.springframework.cache : TRACE
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind : TRACE